[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["node_modules/**"]

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm start"